version: '3'

networks:
  nginx-php74-mysql57:

services:

  # nginx
  nginx-serivce:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql57-service
    networks:
      - nginx-php74-mysql57

  # php
  php74-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php74-mysql57

  # mysql
  mysql57-service:
    image: mysql:5.7
    container_name: mysql57-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password #--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      #MYSQL_USER: root
      #MYSQL_DATABASE: url-shortener
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: secret

    networks:
      - nginx-php74-mysql57

  mailer-service:
    image: schickling/mailcatcher
    container_name: mailer-container
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - nginx-php74-mysql57